export const SET_SEARCH_TERM = "SET_SEARCH_TERM";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SET_TOKEN = "SET_TOKEN";
export const SET_USER = "SET_USER";
export const SET_LISTITEM = "SET_LISTITEM";
export const SET_MOSTPLAYED_ALL = "SET_MOSTPLAYED_ALL";
export const SET_MOSTPLAYED_6MONTHS = "SET_MOSTPLAYED_6MONTHS";
export const SET_MOSTPLAYED_3MONTHS = "SET_MOSTPLAYED_3MONTHS";
export const SET_MAIN_VIEW = "SET_MAIN_VIEW";
export const SET_TEMP_VIEW = "SET_TEMP_VIEW";
export const SET_UPLOADER_VIEW = "SET_UPLOADER_VIEW";
export const SET_LIBRARY = "SET_LIBRARY";
export const SET_S3_URL = "SET_S3_URL";
